### ISSUE TITLE
Front-end: UI/UX design & development

### ISSUE THREAD

**Issue by irinamityugova** [irishka2863/SJParks#18]
1. User interface research for modern implementation.
2. Wireframes and features for the About page, adminDashboard, login page, and error pages.
3. React Components
4. Styling
5. Functionality

**Comment by irishka2863** [comment]
React Components are 50% complete: Sidebar, Topnav, Login, Park Addition Form, User Addition Form
Styling is 5% complete: Sidenav
Functionality is 1% complete: onClick toggling of the active state for buttons. Problem: How do we pass the active state of the button in the imported component to App.js, so it feeds the selected HTML into the page?

11/10/18 - The plan is to push raw components: 
1. Graph
2. Posts
3. Search Bar
4. Parks List
5. Users List
6. Account Settings
7. Cover Page
